const headers = require('../utils/auth.js');
const constants = require('../utils/constants.js');
const { createUri, createFields, createBody } = require('../utils/actionHelpers.js');

const fields = [
  { key: 'sourceApp', label: 'Source App', type: "string", required: true },
  { key: 'sourceType', label: 'Source Type', type: "string", required: true },
  { key: 'jobNo', label: 'Job No', type: "string", required: true },
  { key: 'taskNo', label: 'Task No', type: "string", required: true },
  { key: 'taskType', label: 'Task Type', type: "string", required: true },
  { key: 'shortDescription', label: 'Short Description', type: "string", required: true },
  { key: 'description', label: 'Description', type: "string", required: true },
  { key: 'name', label: 'Name', type: "string", required: true },
  { key: 'type', label: 'Type', type: "string", required: true },
  { key: 'category', label: 'Category', type: "string", required: true },
  { key: 'timeMarker', label: 'Time Marker', type: "string", required: true },
  { key: 'pin', label: 'Pin', type: "string", required: true },
  { key: 'serviceNo', label: 'Service No', type: "string", required: true },
  { key: 'serviceGroup', label: 'Service Group', type: "string", required: true },
  { key: 'serviceClass', label: 'Service Class', type: "string", required: true },
  { key: 'serviceSerialNo', label: 'Service Serial No', type: "string", required: true },
  { key: 'serviceName', label: 'Service Name', type: "string", required: true },
  { key: 'irisfault', label: 'IRISFault', type: "string", required: true },
  { key: 'irissymptom', label: 'IRISSymptom', type: "string", required: true },
  { key: 'irisarea', label: 'IRISArea', type: "string", required: true },
  { key: 'irisreason', label: 'IRISReason', type: "string", required: true },
  { key: 'irisresolution', label: 'IRISResolution', type: "string", required: true },
  { key: 'skill1', label: 'Skill1', type: "string", required: true },
  { key: 'skill2', label: 'Skill2', type: "string", required: true },
  { key: 'skill3', label: 'Skill3', type: "string", required: true },
  { key: 'contractNo', label: 'Contract No', type: "string", required: true },
  { key: 'contractType', label: 'Contract Type', type: "string", required: true },
  { key: 'contractDescription', label: 'Contract Description', type: "string", required: true },
  { key: 'contractStartDate', label: 'Contract Start Date', type: "string", required: true },
  { key: 'contractEndDate', label: 'Contract End Date', type: "string", required: true },
  { key: 'partsWarrantyStartDate', label: 'Parts Warranty Start Date', type: "string", required: true },
  { key: 'partsWarrantyEndDate', label: 'Parts Warranty End Date', type: "string", required: true },
  { key: 'laborWarrantyStartDate', label: 'Labor Warranty Start Date', type: "string", required: true },
  { key: 'laborWarrantyEndDate', label: 'Labor Warranty End Date', type: "string", required: true },
  { key: 'importance', label: 'Importance', type: "string", required: true },
  { key: 'status', label: 'Status', type: "string", required: true },
  { key: 'expectedResponseDateTime', label: 'Expected Response Date Time', type: "string", required: true },
  { key: 'actualResponseDateTime', label: 'Actual Response Date Time', type: "string", required: true },
  { key: 'requestedStartDate', label: 'Requested Start Date', type: "string", required: true },
  { key: 'requestedEndDate', label: 'Requested End Date', type: "string", required: true },
  { key: 'requestedStartTime', label: 'Requested Start Time', type: "string", required: true },
  { key: 'requestedEndTime', label: 'Requested End Time', type: "string", required: true },
  { key: 'confirmedStartDate', label: 'Confirmed Start Date', type: "string", required: true },
  { key: 'confirmedEndDate', label: 'Confirmed End Date', type: "string", required: true },
  { key: 'actualStartDate', label: 'Actual Start Date', type: "string", required: true },
  { key: 'actualEndDate', label: 'Actual End Date', type: "string", required: true },
  { key: 'locationDescription', label: 'Location Description', type: "string", required: true },
  { key: 'duration', label: 'Duration', type: "string", required: true },
  { key: 'durationInSeconds', label: 'Duration In Seconds', type: "string", required: true },
  { key: 'subject', label: 'Subject', type: "string", required: true },
  { key: 'body', label: 'Body', type: "string", required: true },
  { key: 'infiniteTask', label: 'Infinite Task', type: "string", required: true },
  { key: 'taskOpenAsOf', label: 'Task Open As Of', type: "string", required: true },
  { key: 'taskOpenTill', label: 'Task Open Till', type: "string", required: true },
  { key: 'requiredTotalDuration', label: 'Required Total Duration', type: "string", required: true },
  { key: 'requiredNoResources', label: 'Required No Resources', type: "string", required: true },
  { key: 'appointmentEarliestAllowed', label: 'Appointment Earliest Allowed', type: "string", required: true },
  { key: 'appointmentLatestAllowed', label: 'Appointment Latest Allowed', type: "string", required: true },
  { key: 'freeText1', label: 'Free Text1', type: "string", required: true },
  { key: 'freeText2', label: 'Free Text2', type: "string", required: true },
  { key: 'freeText3', label: 'Free Text3', type: "string", required: true },
  { key: 'freeText4', label: 'Free Text4', type: "string", required: true },
  { key: 'freeText5', label: 'Free Text5', type: "string", required: true },
  { key: 'freeText6', label: 'Free Text6', type: "string", required: true },
  { key: 'freeText7', label: 'Free Text7', type: "string", required: true },
  { key: 'freeText8', label: 'Free Text8', type: "string", required: true },
  { key: 'freeText9', label: 'Free Text9', type: "string", required: true },
  { key: 'freeText10', label: 'Free Text10', type: "string", required: true },
  { key: 'freeText11', label: 'Free Text11', type: "string", required: true },
  { key: 'freeText12', label: 'Free Text12', type: "string", required: true },
  { key: 'freeText13', label: 'Free Text13', type: "string", required: true },
  { key: 'freeText14', label: 'Free Text14', type: "string", required: true },
  { key: 'freeText15', label: 'Free Text15', type: "string", required: true },
  { key: 'freeText16', label: 'Free Text16', type: "string", required: true },
  { key: 'freeText17', label: 'Free Text17', type: "string", required: true },
  { key: 'freeText18', label: 'Free Text18', type: "string", required: true },
  { key: 'freeText19', label: 'Free Text19', type: "string", required: true },
  { key: 'freeText20', label: 'Free Text20', type: "string", required: true },
  { key: 'freeDecimal1', label: 'Free Decimal1', type: "string", required: true },
  { key: 'freeDecimal2', label: 'Free Decimal2', type: "string", required: true },
  { key: 'freeDecimal3', label: 'Free Decimal3', type: "string", required: true },
  { key: 'freeDecimal4', label: 'Free Decimal4', type: "string", required: true },
  { key: 'freeDecimal5', label: 'Free Decimal5', type: "string", required: true },
  { key: 'freeDate1', label: 'Free Date1', type: "string", required: true },
  { key: 'freeDate2', label: 'Free Date2', type: "string", required: true },
  { key: 'freeDate3', label: 'Free Date3', type: "string", required: true },
  { key: 'freeDate4', label: 'Free Date4', type: "string", required: true },
  { key: 'freeDate5', label: 'Free Date5', type: "string", required: true },
  { key: 'freeBit1', label: 'Free Bit1', type: "string", required: true },
  { key: 'freeBit2', label: 'Free Bit2', type: "string", required: true },
  { key: 'freeBit3', label: 'Free Bit3', type: "string", required: true },
  { key: 'freeBit4', label: 'Free Bit4', type: "string", required: true },
  { key: 'freeBit5', label: 'Free Bit5', type: "string", required: true },
  { key: 'url1', label: 'url1', type: "string", required: true },
  { key: 'urldesc1', label: 'urldesc1', type: "string", required: true },
  { key: 'url2', label: 'url2', type: "string", required: true },
  { key: 'urldesc2', label: 'urldesc2', type: "string", required: true },
  { key: 'url3', label: 'url3', type: "string", required: true },
  { key: 'urldesc3', label: 'urldesc3', type: "string", required: true },
  { key: 'certificateNo', label: 'Certificate No', type: "string", required: true },
  { key: 'requiredTotalDurationInSeconds', label: 'Required Total Duration In Seconds', type: "string", required: true },
  { key: 'doNotCountAppointmentResource', label: 'Do Not Count Appointment Resource', type: "string", required: true },
  { key: 'isComplete', label: 'Is Complete', type: "string", required: true },
  { key: 'planningUom', label: 'Planning UOM', type: "string", required: true },
  { key: 'planningUomconversion', label: 'Planning UOMConversion', type: "string", required: true },
  { key: 'planningQty', label: 'Planning Qty', type: "string", required: true },
  { key: 'useFixPlanningQty', label: 'Use Fix Planning Qty', type: "string", required: true },
  { key: 'roundToUom', label: 'Round To UOM', type: "string", required: true },
  { key: 'appointmentTemplate', label: 'Appointment Template', type: "string", required: true },
  { key: 'bulkPlanningQty', label: 'Bulk Planning Qty', type: "string", required: true },
  { key: 'startDate', label: 'Start Date', type: "string", required: true },
  { key: 'endDate', label: 'End Date', type: "string", required: true },
  { key: 'percentDone', label: 'Percent Done', type: "string", required: true },
  { key: 'schedulingMode', label: 'Scheduling Mode', type: "string", required: true },
  { key: 'baseLineStartDate', label: 'Base Line Start Date', type: "string", required: true },
  { key: 'baseLineEndDate', label: 'Base Line End Date', type: "string", required: true },
  { key: 'baseLinePercentDone', label: 'Base Line Percent Done', type: "string", required: true },
  { key: 'deadLine', label: 'Dead Line', type: "string", required: true },
  { key: 'index', label: 'Index', type: "string", required: true },
  { key: 'constraintType', label: 'Constraint Type', type: "string", required: true },
  { key: 'constraintDate', label: 'Constraint Date', type: "string", required: true },
  { key: 'parentTaskNo', label: 'Parent Task No', type: "string", required: true },
  { key: 'calendarCode', label: 'Calendar Code', type: "string", required: true },
  { key: 'predecessorTaskNo', label: 'Predecessor Task No', type: "string", required: true },
  { key: 'predecessorLag', label: 'Predecessor Lag', type: "string", required: true },
  { key: 'manuallyScheduled', label: 'Manually Scheduled', type: "string", required: true },
  { key: 'note', label: 'Note', type: "string", required: true },
  { key: 'overRuleGanttPlanning', label: 'Over Rule Gantt Planning', type: "string", required: true },
  { key: 'ignoreCalendars', label: 'Ignore Calendars', type: "string", required: true },
  { key: 'containerName', label: 'Container Name', type: "string", required: true },
  { key: 'containerIndex', label: 'Container Index', type: "string", required: true },
];

module.exports = {
  key: 'save_task',
  noun: 'Task',
  display: {
    label: 'Set task',
    description: 'Saves the task.',
    hidden: false,
    important: true,
  },
  operation: {
    inputFields: createFields(fields),
    perform: {
      url: createUri(constants.endpoints.task),
      method: 'POST',
      headers,
      body: createBody(fields),
    },
  },
};
