const headers = require('../utils/auth.js');
const constants = require('../utils/constants.js');
const { createUri, createFields, createBody } = require('../utils/actionHelpers.js');

const fields = [
  { key: 'resourceTypeId', label: 'Resource Type Id', type: "string", required: true },
  { key: 'sourceApp', label: 'Source App', type: "string", required: true },
  { key: 'sourceType', label: 'Source Type', type: "string", required: true },
  { key: 'resourceType', label: 'Resource Type', type: "string", required: true },
  { key: 'resourceName', label: 'Resource Name', type: "string", required: true },
  { key: 'displayName', label: 'Display Name', type: "string", required: true },
  { key: 'department', label: 'Department', type: "string", required: true },
  { key: 'resourceNo', label: 'Resource No', type: "string", required: true },
  { key: 'email', label: 'Email', type: "string", required: true },
  { key: 'phone', label: 'Phone', type: "string", required: true },
  { key: 'mobilePhone', label: 'Mobile Phone', type: "string", required: true },
  { key: 'replacementResource', label: 'Replacement Resource', type: "string", required: true },
  { key: 'fieldServiceEmail', label: 'Field Service Email', type: "string", required: true },
  { key: 'personalEmail', label: 'Personal Email', type: "string", required: true },
  { key: 'gpsTrackingResourceNo', label: 'Gps Tracking Resource No', type: "string", required: true },
  { key: 'homeAddress', label: 'Home Address', type: "string", required: true },
  { key: 'homeAddressGeoLong', label: 'Home Address Geo Long', type: "string", required: true },
  { key: 'homeAddressGeoLat', label: 'Home Address Geo Lat', type: "string", required: true },
  { key: 'homePhone', label: 'Home Phone', type: "string", required: true },
  { key: 'homeEmail', label: 'Home Email', type: "string", required: true },
  { key: 'homeRegion', label: 'Home Region', type: "string", required: true },
  { key: 'homePostcode', label: 'Home Postcode', type: "string", required: true },
  { key: 'homeCity', label: 'Home City', type: "string", required: true },
  { key: 'homeCounty', label: 'Home County', type: "string", required: true },
  { key: 'homeState', label: 'Home State', type: "string", required: true },
  { key: 'homeCountry', label: 'Home Country', type: "string", required: true },
  { key: 'teamCode', label: 'Team Code', type: "string", required: true },
  { key: 'teamName', label: 'Team Name', type: "string", required: true },
  { key: 'teamType', label: 'Team Type', type: "string", required: true },
  { key: 'teamSort', label: 'Team Sort', type: "string", required: true },
  { key: 'teamMemberType', label: 'Team Member Type', type: "string", required: true },
  { key: 'teamMemberSort', label: 'Team Member Sort', type: "string", required: true },
  { key: 'freeText1', label: 'Free Text1', type: "string", required: true },
  { key: 'freeText2', label: 'Free Text2', type: "string", required: true },
  { key: 'freeText3', label: 'Free Text3', type: "string", required: true },
  { key: 'freeText4', label: 'Free Text4', type: "string", required: true },
  { key: 'freeText5', label: 'Free Text5', type: "string", required: true },
  { key: 'freeText6', label: 'Free Text6', type: "string", required: true },
  { key: 'freeText7', label: 'Free Text7', type: "string", required: true },
  { key: 'freeText8', label: 'Free Text8', type: "string", required: true },
  { key: 'freeText9', label: 'Free Text9', type: "string", required: true },
  { key: 'freeText10', label: 'Free Text10', type: "string", required: true },
  { key: 'freeText11', label: 'Free Text11', type: "string", required: true },
  { key: 'freeText12', label: 'Free Text12', type: "string", required: true },
  { key: 'freeText13', label: 'Free Text13', type: "string", required: true },
  { key: 'freeText14', label: 'Free Text14', type: "string", required: true },
  { key: 'freeText15', label: 'Free Text15', type: "string", required: true },
  { key: 'freeText16', label: 'Free Text16', type: "string", required: true },
  { key: 'freeText17', label: 'Free Text17', type: "string", required: true },
  { key: 'freeText18', label: 'Free Text18', type: "string", required: true },
  { key: 'freeText19', label: 'Free Text19', type: "string", required: true },
  { key: 'freeText20', label: 'Free Text20', type: "string", required: true },
  { key: 'freeDecimal1', label: 'Free Decimal1', type: "string", required: true },
  { key: 'freeDecimal2', label: 'Free Decimal2', type: "string", required: true },
  { key: 'freeDecimal3', label: 'Free Decimal3', type: "string", required: true },
  { key: 'freeDecimal4', label: 'Free Decimal4', type: "string", required: true },
  { key: 'freeDecimal5', label: 'Free Decimal5', type: "string", required: true },
  { key: 'freeDecimal6', label: 'Free Decimal6', type: "string", required: true },
  { key: 'freeDecimal7', label: 'Free Decimal7', type: "string", required: true },
  { key: 'freeDecimal8', label: 'Free Decimal8', type: "string", required: true },
  { key: 'freeDecimal9', label: 'Free Decimal9', type: "string", required: true },
  { key: 'freeDecimal10', label: 'Free Decimal10', type: "string", required: true },
  { key: 'freeDate1', label: 'Free Date1', type: "string", required: true },
  { key: 'freeDate2', label: 'Free Date2', type: "string", required: true },
  { key: 'freeDate3', label: 'Free Date3', type: "string", required: true },
  { key: 'freeDate4', label: 'Free Date4', type: "string", required: true },
  { key: 'freeDate5', label: 'Free Date5', type: "string", required: true },
  { key: 'freeBit1', label: 'Free Bit1', type: "string", required: true },
  { key: 'freeBit2', label: 'Free Bit2', type: "string", required: true },
  { key: 'freeBit3', label: 'Free Bit3', type: "string", required: true },
  { key: 'freeBit4', label: 'Free Bit4', type: "string", required: true },
  { key: 'freeBit5', label: 'Free Bit5', type: "string", required: true },
  { key: 'doNotShow', label: 'Do Not Show', type: "string", required: true },
  { key: 'inServiceFrom', label: 'In Service From', type: "string", required: true },
  { key: 'inServiceTill', label: 'In Service Till', type: "string", required: true },
  { key: 'exchangeIntegrationEnabled', label: 'Exchange Integration Enabled', type: "string", required: true },
  { key: 'url1', label: 'url1', type: "string", required: true },
  { key: 'urldesc1', label: 'urldesc1', type: "string", required: true },
  { key: 'url2', label: 'url2', type: "string", required: true },
  { key: 'urldesc2', label: 'urldesc2', type: "string", required: true },
  { key: 'url3', label: 'url3', type: "string", required: true },
  { key: 'urldesc3', label: 'urldesc3', type: "string", required: true },
  { key: 'bulkPlanning', label: 'Bulk Planning', type: "string", required: true },
  { key: 'bulkCapacity', label: 'Bulk Capacity', type: "string", required: true },
  { key: 'resourceGpsTrackingEnabled', label: 'Resource Gps Tracking Enabled', type: "string", required: true },
  { key: 'pin', label: 'Pin', type: "string", required: true }
];

module.exports = {
  key: 'save_resource',
  noun: 'Resource',
  display: {
    label: 'Set resource',
    description: 'Saves the resource.',
    hidden: false,
    important: true,
  },
  operation: {
    inputFields: createFields(fields),
    perform: {
      url: createUri(constants.endpoints.resource),
      method: 'POST',
      headers,
      body: createBody(fields),
    },
  },
};
