const { createAction } = require('../utils/actionBuilder.js');
const constants = require('../utils/constants.js');

const fields = [
  { key: 'sourceApp', label: 'SourceApp', type: "string" },
  { key: 'sourceType', label: 'SourceType', type: "string" },
  { key: 'jobNo', label: 'JobNo', type: "string" },
  { key: 'shortDescription', label: 'ShortDescription', type: "string" },
  { key: 'description', label: 'Description', type: "string" },
  { key: 'type', label: 'Type', type: "integer" },
  { key: 'name', label: 'Name', type: "string" },
  { key: 'category', label: 'Category', type: "string" },
  { key: 'timeMarker', label: 'TimeMarker', type: "string" },
  { key: 'pin', label: 'Pin', type: "string" },
  { key: 'customerNo', label: 'CustomerNo', type: "string" },
  { key: 'customerName', label: 'CustomerName', type: "string" },
  { key: 'customerAddress', label: 'CustomerAddress', type: "string" },
  { key: 'customerAddressGeoLong', label: 'CustomerAddressGeoLong', type: "string" },
  { key: 'customerAddressGeoLat', label: 'CustomerAddressGeoLat', type: "string" },
  { key: 'customerPhone', label: 'CustomerPhone', type: "string" },
  { key: 'customerEmail', label: 'CustomerEmail', type: "string" },
  { key: 'contactNo', label: 'ContactNo', type: "string" },
  { key: 'contactName', label: 'ContactName', type: "string" },
  { key: 'contactAddress', label: 'ContactAddress', type: "string" },
  { key: 'contactAddressGeoLong', label: 'ContactAddressGeoLong', type: "string" },
  { key: 'contactAddressGeoLat', label: 'ContactAddressGeoLat', type: "string" },
  { key: 'contactPhone', label: 'ContactPhone', type: "string" },
  { key: 'contactEmail', label: 'ContactEmail', type: "string" },
  { key: 'siteNo', label: 'SiteNo', type: "string" },
  { key: 'siteName', label: 'SiteName', type: "string" },
  { key: 'siteAddress', label: 'SiteAddress', type: "string" },
  { key: 'siteAddressGeoLong', label: 'SiteAddressGeoLong', type: "string" },
  { key: 'siteAddressGeoLat', label: 'SiteAddressGeoLat', type: "string" },
  { key: 'sitePhone', label: 'SitePhone', type: "string" },
  { key: 'siteEmail', label: 'SiteEmail', type: "string" },
  { key: 'siteRegion', label: 'SiteRegion', type: "string" },
  { key: 'siteStreet', label: 'SiteStreet', type: "string" },
  { key: 'siteStreetNo', label: 'SiteStreetNo', type: "string" },
  { key: 'sitePostcode', label: 'SitePostcode', type: "string" },
  { key: 'siteCity', label: 'SiteCity', type: "string" },
  { key: 'siteCounty', label: 'SiteCounty', type: "string" },
  { key: 'siteState', label: 'SiteState', type: "string" },
  { key: 'siteCountry', label: 'SiteCountry', type: "string" },
  { key: 'siteFromNo', label: 'SiteFromNo', type: "string" },
  { key: 'siteFromName', label: 'SiteFromName', type: "string" },
  { key: 'siteFromAddress', label: 'SiteFromAddress', type: "string" },
  { key: 'siteFromAddressGeoLong', label: 'SiteFromAddressGeoLong', type: "string" },
  { key: 'siteFromAddressGeoLat', label: 'SiteFromAddressGeoLat', type: "string" },
  { key: 'siteFromPhone', label: 'SiteFromPhone', type: "string" },
  { key: 'siteFromEmail', label: 'SiteFromEmail', type: "string" },
  { key: 'siteFromRegion', label: 'SiteFromRegion', type: "string" },
  { key: 'siteFromStreet', label: 'SiteFromStreet', type: "string" },
  { key: 'siteFromStreetNo', label: 'SiteFromStreetNo', type: "string" },
  { key: 'siteFromPostcode', label: 'SiteFromPostcode', type: "string" },
  { key: 'siteFromCity', label: 'SiteFromCity', type: "string" },
  { key: 'siteFromCounty', label: 'SiteFromCounty', type: "string" },
  { key: 'siteFromState', label: 'SiteFromState', type: "string" },
  { key: 'siteFromCountry', label: 'SiteFromCountry', type: "string" },
  { key: 'billNo', label: 'BillNo', type: "string" },
  { key: 'billName', label: 'BillName', type: "string" },
  { key: 'billAddress', label: 'BillAddress', type: "string" },
  { key: 'billAddressGeoLong', label: 'BillAddressGeoLong', type: "string" },
  { key: 'billAddressGeoLat', label: 'BillAddressGeoLat', type: "string" },
  { key: 'billPhone', label: 'BillPhone', type: "string" },
  { key: 'billEmail', label: 'BillEmail', type: "string" },
  { key: 'billRegion', label: 'BillRegion', type: "string" },
  { key: 'importance', label: 'Importance', type: "string" },
  { key: 'creationDateTime', label: 'CreationDateTime', type: "string" },
  { key: 'customerReference', label: 'CustomerReference', type: "string" },
  { key: 'language', label: 'Language', type: "string" },
  { key: 'responsible', label: 'Responsible', type: "string" },
  { key: 'creator', label: 'Creator', type: "string" },
  { key: 'freeText1', label: 'FreeText1', type: "string" },
  { key: 'freeText2', label: 'FreeText2', type: "string" },
  { key: 'freeText3', label: 'FreeText3', type: "string" },
  { key: 'freeText4', label: 'FreeText4', type: "string" },
  { key: 'freeText5', label: 'FreeText5', type: "string" },
  { key: 'freeText6', label: 'FreeText6', type: "string" },
  { key: 'freeText7', label: 'FreeText7', type: "string" },
  { key: 'freeText8', label: 'FreeText8', type: "string" },
  { key: 'freeText9', label: 'FreeText9', type: "string" },
  { key: 'freeText10', label: 'FreeText10', type: "string" },
  { key: 'freeText11', label: 'FreeText11', type: "string" },
  { key: 'freeText12', label: 'FreeText12', type: "string" },
  { key: 'freeText13', label: 'FreeText13', type: "string" },
  { key: 'freeText14', label: 'FreeText14', type: "string" },
  { key: 'freeText15', label: 'FreeText15', type: "string" },
  { key: 'freeText16', label: 'FreeText16', type: "string" },
  { key: 'freeText17', label: 'FreeText17', type: "string" },
  { key: 'freeText18', label: 'FreeText18', type: "string" },
  { key: 'freeText19', label: 'FreeText19', type: "string" },
  { key: 'freeText20', label: 'FreeText20', type: "string" },
  { key: 'freeDecimal1', label: 'FreeDecimal1', type: "string" },
  { key: 'freeDecimal2', label: 'FreeDecimal2', type: "string" },
  { key: 'freeDecimal3', label: 'FreeDecimal3', type: "string" },
  { key: 'freeDecimal4', label: 'FreeDecimal4', type: "string" },
  { key: 'freeDecimal5', label: 'FreeDecimal5', type: "string" },
  { key: 'freeDate1', label: 'FreeDate1', type: "string" },
  { key: 'freeDate2', label: 'FreeDate2', type: "string" },
  { key: 'freeDate3', label: 'FreeDate3', type: "string" },
  { key: 'freeDate4', label: 'FreeDate4', type: "string" },
  { key: 'freeDate5', label: 'FreeDate5', type: "string" },
  { key: 'freeBit1', label: 'FreeBit1', type: "boolean" },
  { key: 'freeBit2', label: 'FreeBit2', type: "boolean" },
  { key: 'freeBit3', label: 'FreeBit3', type: "boolean" },
  { key: 'freeBit4', label: 'FreeBit4', type: "boolean" },
  { key: 'freeBit5', label: 'FreeBit5', type: "boolean" },
  { key: 'enableManualSelection', label: 'EnableManualSelection', type: "boolean" },
  { key: 'availableInGantt', label: 'AvailableInGantt', type: "boolean" },
  { key: 'startDate', label: 'StartDate', type: "datetime" },
  { key: 'endDate', label: 'EndDate', type: "datetime" },
  { key: 'allowDependencies', label: 'AllowDependencies', type: "boolean" },
  { key: 'note', label: 'Note', type: "string" },
  { key: 'overRuleGanttPlanning', label: 'OverRuleGanttPlanning', type: "string" },
  { key: 'checkAppointments', label: 'CheckAppointments', type: "string" },
  { key: 'sentFromBackOffice', label: 'SentFromBackOffice', type: "string" },
  { key: 'readOnly', label: 'ReadOnly', type: "string" },
];

const sample = {
  sourceApp: 'ZAPIER',
  sourceType: 'DEMO',
  jobNo: 'DS_DEMO',
  shortDescription: 'Hi from Zapier test suite',
  description: 'Hi from Zapier test suite'
};


module.exports = createAction(
  constants.endpoints.job,
  'save_job',
  'Job',
  'Save job',
  'Saves a job',
  fields,
  sample
);