const headers = require('../utils/auth.js');
const constants = require('../utils/constants.js');
const { createUri, createFields, createBody } = require('../utils/actionHelpers.js');

const fields = [
  { key: 'sourceApp', label: 'SourceApp', type: "string", required: false },
  { key: 'sourceType', label: 'SourceType', type: "string", required: false },
  { key: 'jobNo', label: 'JobNo', type: "string", required: false },
  { key: 'shortDescription', label: 'ShortDescription', type: "string", required: false },
  { key: 'description', label: 'Description', type: "string", required: false },
  { key: 'type', label: 'Type', type: "string", required: false },
  { key: 'name', label: 'Name', type: "string", required: false },
  { key: 'category', label: 'Category', type: "string", required: false },
  { key: 'timeMarker', label: 'TimeMarker', type: "string", required: false },
  { key: 'pin', label: 'Pin', type: "string", required: false },
  { key: 'customerNo', label: 'CustomerNo', type: "string", required: false },
  { key: 'customerName', label: 'CustomerName', type: "string", required: false },
  { key: 'customerAddress', label: 'CustomerAddress', type: "string", required: false },
  { key: 'customerAddressGeoLong', label: 'CustomerAddressGeoLong', type: "string", required: false },
  { key: 'customerAddressGeoLat', label: 'CustomerAddressGeoLat', type: "string", required: false },
  { key: 'customerPhone', label: 'CustomerPhone', type: "string", required: false },
  { key: 'customerEmail', label: 'CustomerEmail', type: "string", required: false },
  { key: 'contactNo', label: 'ContactNo', type: "string", required: false },
  { key: 'contactName', label: 'ContactName', type: "string", required: false },
  { key: 'contactAddress', label: 'ContactAddress', type: "string", required: false },
  { key: 'contactAddressGeoLong', label: 'ContactAddressGeoLong', type: "string", required: false },
  { key: 'contactAddressGeoLat', label: 'ContactAddressGeoLat', type: "string", required: false },
  { key: 'contactPhone', label: 'ContactPhone', type: "string", required: false },
  { key: 'contactEmail', label: 'ContactEmail', type: "string", required: false },
  { key: 'siteNo', label: 'SiteNo', type: "string", required: false },
  { key: 'siteName', label: 'SiteName', type: "string", required: false },
  { key: 'siteAddress', label: 'SiteAddress', type: "string", required: false },
  { key: 'siteAddressGeoLong', label: 'SiteAddressGeoLong', type: "string", required: false },
  { key: 'siteAddressGeoLat', label: 'SiteAddressGeoLat', type: "string", required: false },
  { key: 'sitePhone', label: 'SitePhone', type: "string", required: false },
  { key: 'siteEmail', label: 'SiteEmail', type: "string", required: false },
  { key: 'siteRegion', label: 'SiteRegion', type: "string", required: false },
  { key: 'siteStreet', label: 'SiteStreet', type: "string", required: false },
  { key: 'siteStreetNo', label: 'SiteStreetNo', type: "string", required: false },
  { key: 'sitePostcode', label: 'SitePostcode', type: "string", required: false },
  { key: 'siteCity', label: 'SiteCity', type: "string", required: false },
  { key: 'siteCounty', label: 'SiteCounty', type: "string", required: false },
  { key: 'siteState', label: 'SiteState', type: "string", required: false },
  { key: 'siteCountry', label: 'SiteCountry', type: "string", required: false },
  { key: 'siteFromNo', label: 'SiteFromNo', type: "string", required: false },
  { key: 'siteFromName', label: 'SiteFromName', type: "string", required: false },
  { key: 'siteFromAddress', label: 'SiteFromAddress', type: "string", required: false },
  { key: 'siteFromAddressGeoLong', label: 'SiteFromAddressGeoLong', type: "string", required: false },
  { key: 'siteFromAddressGeoLat', label: 'SiteFromAddressGeoLat', type: "string", required: false },
  { key: 'siteFromPhone', label: 'SiteFromPhone', type: "string", required: false },
  { key: 'siteFromEmail', label: 'SiteFromEmail', type: "string", required: false },
  { key: 'siteFromRegion', label: 'SiteFromRegion', type: "string", required: false },
  { key: 'siteFromStreet', label: 'SiteFromStreet', type: "string", required: false },
  { key: 'siteFromStreetNo', label: 'SiteFromStreetNo', type: "string", required: false },
  { key: 'siteFromPostcode', label: 'SiteFromPostcode', type: "string", required: false },
  { key: 'siteFromCity', label: 'SiteFromCity', type: "string", required: false },
  { key: 'siteFromCounty', label: 'SiteFromCounty', type: "string", required: false },
  { key: 'siteFromState', label: 'SiteFromState', type: "string", required: false },
  { key: 'siteFromCountry', label: 'SiteFromCountry', type: "string", required: false },
  { key: 'billNo', label: 'BillNo', type: "string", required: false },
  { key: 'billName', label: 'BillName', type: "string", required: false },
  { key: 'billAddress', label: 'BillAddress', type: "string", required: false },
  { key: 'billAddressGeoLong', label: 'BillAddressGeoLong', type: "string", required: false },
  { key: 'billAddressGeoLat', label: 'BillAddressGeoLat', type: "string", required: false },
  { key: 'billPhone', label: 'BillPhone', type: "string", required: false },
  { key: 'billEmail', label: 'BillEmail', type: "string", required: false },
  { key: 'billRegion', label: 'BillRegion', type: "string", required: false },
  { key: 'importance', label: 'Importance', type: "string", required: false },
  { key: 'creationDateTime', label: 'CreationDateTime', type: "string", required: false },
  { key: 'customerReference', label: 'CustomerReference', type: "string", required: false },
  { key: 'language', label: 'Language', type: "string", required: false },
  { key: 'responsible', label: 'Responsible', type: "string", required: false },
  { key: 'creator', label: 'Creator', type: "string", required: false },
  { key: 'freeText1', label: 'FreeText1', type: "string", required: false },
  { key: 'freeText2', label: 'FreeText2', type: "string", required: false },
  { key: 'freeText3', label: 'FreeText3', type: "string", required: false },
  { key: 'freeText4', label: 'FreeText4', type: "string", required: false },
  { key: 'freeText5', label: 'FreeText5', type: "string", required: false },
  { key: 'freeText6', label: 'FreeText6', type: "string", required: false },
  { key: 'freeText7', label: 'FreeText7', type: "string", required: false },
  { key: 'freeText8', label: 'FreeText8', type: "string", required: false },
  { key: 'freeText9', label: 'FreeText9', type: "string", required: false },
  { key: 'freeText10', label: 'FreeText10', type: "string", required: false },
  { key: 'freeText11', label: 'FreeText11', type: "string", required: false },
  { key: 'freeText12', label: 'FreeText12', type: "string", required: false },
  { key: 'freeText13', label: 'FreeText13', type: "string", required: false },
  { key: 'freeText14', label: 'FreeText14', type: "string", required: false },
  { key: 'freeText15', label: 'FreeText15', type: "string", required: false },
  { key: 'freeText16', label: 'FreeText16', type: "string", required: false },
  { key: 'freeText17', label: 'FreeText17', type: "string", required: false },
  { key: 'freeText18', label: 'FreeText18', type: "string", required: false },
  { key: 'freeText19', label: 'FreeText19', type: "string", required: false },
  { key: 'freeText20', label: 'FreeText20', type: "string", required: false },
  { key: 'freeDecimal1', label: 'FreeDecimal1', type: "string", required: false },
  { key: 'freeDecimal2', label: 'FreeDecimal2', type: "string", required: false },
  { key: 'freeDecimal3', label: 'FreeDecimal3', type: "string", required: false },
  { key: 'freeDecimal4', label: 'FreeDecimal4', type: "string", required: false },
  { key: 'freeDecimal5', label: 'FreeDecimal5', type: "string", required: false },
  { key: 'freeDate1', label: 'FreeDate1', type: "string", required: false },
  { key: 'freeDate2', label: 'FreeDate2', type: "string", required: false },
  { key: 'freeDate3', label: 'FreeDate3', type: "string", required: false },
  { key: 'freeDate4', label: 'FreeDate4', type: "string", required: false },
  { key: 'freeDate5', label: 'FreeDate5', type: "string", required: false },
  { key: 'freeBit1', label: 'FreeBit1', type: "string", required: false },
  { key: 'freeBit2', label: 'FreeBit2', type: "string", required: false },
  { key: 'freeBit3', label: 'FreeBit3', type: "string", required: false },
  { key: 'freeBit4', label: 'FreeBit4', type: "string", required: false },
  { key: 'freeBit5', label: 'FreeBit5', type: "string", required: false },
  { key: 'enableManualSelection', label: 'EnableManualSelection', type: "string", required: false },
  { key: 'availableInGantt', label: 'AvailableInGantt', type: "string", required: false },
  { key: 'startDate', label: 'StartDate', type: "string", required: false },
  { key: 'endDate', label: 'EndDate', type: "string", required: false },
  { key: 'allowDependencies', label: 'AllowDependencies', type: "string", required: false },
  { key: 'note', label: 'Note', type: "string", required: false },
  { key: 'overRuleGanttPlanning', label: 'OverRuleGanttPlanning', type: "string", required: false },
  { key: 'checkAppointments', label: 'CheckAppointments', type: "string", required: false },
  { key: 'sentFromBackOffice', label: 'SentFromBackOffice', type: "string", required: false },
  { key: 'readOnly', label: 'ReadOnly', type: "string", required: false },
];

module.exports = {
  key: 'save_job',
  noun: 'Job',
  display: {
    label: 'Set job',
    description: 'Saves the job.',
    hidden: false,
    important: true,
  },
  operation: {
    inputFields: createFields(fields),
    perform: {
      url: createUri(constants.endpoints.job),
      method: 'POST',
      headers,
      body: createBody(fields),
    },
  },
};
