const headers = require('../utils/auth.js');
const constants = require('../utils/constants.js');
const { createUri, createFields, createBody } = require('../utils/actionHelpers.js');

const fields = [
  { key: 'resourceNo', label: 'ResourceNo', type: "string", required: true },
  { key: 'sourceApp', label: 'SourceApp', type: "string", required: false },
  { key: 'sourceType', label: 'SourceType', type: "string", required: false },
  { key: 'resourceType', label: 'ResourceType', type: "string", required: false },
  { key: 'resourceTypeId', label: 'ResourceTypeId', type: "string", required: false },
  { key: 'resourceName', label: 'ResourceName', type: "string", required: false },
  { key: 'displayName', label: 'DisplayName', type: "string", required: false },
  { key: 'department', label: 'Department', type: "string", required: false },
  { key: 'email', label: 'Email', type: "string", required: false },
  { key: 'phone', label: 'Phone', type: "string", required: false },
  { key: 'mobilePhone', label: 'MobilePhone', type: "string", required: false },
  { key: 'replacementResource', label: 'ReplacementResource', type: "string", required: false },
  { key: 'fieldServiceEmail', label: 'FieldServiceEmail', type: "string", required: false },
  { key: 'personalEmail', label: 'PersonalEmail', type: "string", required: false },
  { key: 'gpsTrackingResourceNo', label: 'GpsTrackingResourceNo', type: "string", required: false },
  { key: 'homeAddress', label: 'HomeAddress', type: "string", required: false },
  { key: 'homeAddressGeoLong', label: 'HomeAddressGeoLong', type: "string", required: false },
  { key: 'homeAddressGeoLat', label: 'HomeAddressGeoLat', type: "string", required: false },
  { key: 'homePhone', label: 'HomePhone', type: "string", required: false },
  { key: 'homeEmail', label: 'HomeEmail', type: "string", required: false },
  { key: 'homeStreet', label: 'HomeStreet', type: "string", required: false },
  { key: 'homeStreetNo', label: 'HomeStreetNo', type: "string", required: false },
  { key: 'homePostcode', label: 'HomePostcode', type: "string", required: false },
  { key: 'homeCity', label: 'HomeCity', type: "string", required: false },
  { key: 'homeCounty', label: 'HomeCounty', type: "string", required: false },
  { key: 'homeState', label: 'HomeState', type: "string", required: false },
  { key: 'homeCountry', label: 'HomeCountry', type: "string", required: false },
  { key: 'homeRegion', label: 'HomeRegion', type: "string", required: false },
  { key: 'teamCode', label: 'TeamCode', type: "string", required: false },
  { key: 'teamName', label: 'TeamName', type: "string", required: false },
  { key: 'teamType', label: 'TeamType', type: "string", required: false },
  { key: 'teamSort', label: 'TeamSort', type: "string", required: false },
  { key: 'teamMemberType', label: 'TeamMemberType', type: "string", required: false },
  { key: 'teamMemberSort', label: 'TeamMemberSort', type: "string", required: false },
  { key: 'doNotShow', label: 'DoNotShow', type: "string", required: false },
  { key: 'inServiceFrom', label: 'InServiceFrom', type: "string", required: false },
  { key: 'inServiceTill', label: 'InServiceTill', type: "string", required: false },
  { key: 'exchangeIntegrationEnabled', label: 'ExchangeIntegrationEnabled', type: "string", required: false },
  { key: 'url1', label: 'Url1', type: "string", required: false },
  { key: 'urlDescription1', label: 'UrlDescription1', type: "string", required: false },
  { key: 'url2', label: 'Url2', type: "string", required: false },
  { key: 'urlDescription2', label: 'UrlDescription2', type: "string", required: false },
  { key: 'url3', label: 'Url3', type: "string", required: false },
  { key: 'urlDescription3', label: 'UrlDescription3', type: "string", required: false },
  { key: 'bulkPlanning', label: 'BulkPlanning', type: "string", required: false },
  { key: 'bulkCapacity', label: 'BulkCapacity', type: "string", required: false },
  { key: 'resourceGpsTrackingEnabled', label: 'ResourceGpsTrackingEnabled', type: "string", required: false },
  { key: 'pin', label: 'Pin', type: "string", required: false },
  { key: 'freeText1', label: 'FreeText1', type: "string", required: false },
  { key: 'freeText2', label: 'FreeText2', type: "string", required: false },
  { key: 'freeText3', label: 'FreeText3', type: "string", required: false },
  { key: 'freeText4', label: 'FreeText4', type: "string", required: false },
  { key: 'freeText5', label: 'FreeText5', type: "string", required: false },
  { key: 'freeText6', label: 'FreeText6', type: "string", required: false },
  { key: 'freeText7', label: 'FreeText7', type: "string", required: false },
  { key: 'freeText8', label: 'FreeText8', type: "string", required: false },
  { key: 'freeText9', label: 'FreeText9', type: "string", required: false },
  { key: 'freeText10', label: 'FreeText10', type: "string", required: false },
  { key: 'freeText11', label: 'FreeText11', type: "string", required: false },
  { key: 'freeText12', label: 'FreeText12', type: "string", required: false },
  { key: 'freeText13', label: 'FreeText13', type: "string", required: false },
  { key: 'freeText14', label: 'FreeText14', type: "string", required: false },
  { key: 'freeText15', label: 'FreeText15', type: "string", required: false },
  { key: 'freeText16', label: 'FreeText16', type: "string", required: false },
  { key: 'freeText17', label: 'FreeText17', type: "string", required: false },
  { key: 'freeText18', label: 'FreeText18', type: "string", required: false },
  { key: 'freeText19', label: 'FreeText19', type: "string", required: false },
  { key: 'freeText20', label: 'FreeText20', type: "string", required: false },
  { key: 'freeDecimal1', label: 'FreeDecimal1', type: "string", required: false },
  { key: 'freeDecimal2', label: 'FreeDecimal2', type: "string", required: false },
  { key: 'freeDecimal3', label: 'FreeDecimal3', type: "string", required: false },
  { key: 'freeDecimal4', label: 'FreeDecimal4', type: "string", required: false },
  { key: 'freeDecimal5', label: 'FreeDecimal5', type: "string", required: false },
  { key: 'freeDate1', label: 'FreeDate1', type: "string", required: false },
  { key: 'freeDate2', label: 'FreeDate2', type: "string", required: false },
  { key: 'freeDate3', label: 'FreeDate3', type: "string", required: false },
  { key: 'freeDate4', label: 'FreeDate4', type: "string", required: false },
  { key: 'freeDate5', label: 'FreeDate5', type: "string", required: false },
  { key: 'freeBit1', label: 'FreeBit1', type: "string", required: false },
  { key: 'freeBit2', label: 'FreeBit2', type: "string", required: false },
  { key: 'freeBit3', label: 'FreeBit3', type: "string", required: false },
  { key: 'freeBit4', label: 'FreeBit4', type: "string", required: false },
  { key: 'freeBit5', label: 'FreeBit5', type: "string", required: false },
];

module.exports = {
  key: 'save_resource',
  noun: 'Resource',
  display: {
    label: 'Set resource',
    description: 'Saves the resource.',
    hidden: false,
    important: true,
  },
  operation: {
    inputFields: createFields(fields),
    perform: {
      url: createUri(constants.endpoints.resource.resource),
      method: 'POST',
      headers,
      body: createBody(fields),
    },
  },
};
