module.exports = {
  key: 'save_appointment',
  noun: 'Appointment',
  display: {
    label: 'Save appointment',
    description: 'Saves an appointmnet',
    hidden: false,
    important: true,
  },
  operation: {
    inputFields: [
      {
        key: 'sourceApp',
        label: 'Source App',
        type: 'string',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'sourceType',
        label: 'Source Type',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'jobNo',
        label: 'Job Number',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'taskNo',
        label: 'Task Number',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'resourceNo',
        label: 'Resource Number',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'subject',
        label: 'Subject',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'body',
        label: 'Body',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'start',
        label: 'Start Date',
        type: 'datetime',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'end',
        label: 'End Date',
        type: 'datetime',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
    perform: {
      body: {
        sourceApp: '{{bundle.inputData.sourceApp}}',
        sourceType: '{{bundle.inputData.sourceType}}',
        jobNo: '{{bundle.inputData.jobNo}}',
        taskNo: '{{bundle.inputData.taskNo}}',
        resourceNo: '{{bundle.inputData.resourceNo}}',
        subject: '{{bundle.inputData.subject}}',
        body: '{{bundle.inputData.body}}',
        start: '{{bundle.inputData.start}}',
        end: '{{bundle.inputData.end}}',
      },
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
        'OCP-APIM-SUBSCRIPTION-KEY':
          '{{bundle.authData.Ocp-Apim-Subscription-Key}}',
        'DS-URI': '{{bundle.authData.ds-uri}}',
        'DS-USER': '{{bundle.authData.ds-user}}',
        'DS-PASSWORD': '{{bundle.authData.ds-password}}',
      },
      method: 'POST',
      params: {
        'Ocp-Apim-Subscription-Key':
          '{{bundle.authData.Ocp-Apim-Subscription-Key}}',
        'ds-uri': '{{bundle.authData.ds-uri}}',
        'ds-user': '{{bundle.authData.ds-user}}',
        'ds-password': '{{bundle.authData.ds-password}}',
      },
      url: 'https://api.dimescheduler.com/v0.1/appointment',
    },
  },
};
