const headers = require('../utils/auth.js');
const constants = require('../utils/constants.js');
const { createUri, createFields, createBody } = require('../utils/actionHelpers.js');

const fields = [
  { key: 'sourceApp', label: 'Source App', type: "string", required: true },
  { key: 'sourceType', label: 'Source Type', type: "string", required: true },
  { key: 'jobNo', label: 'Job No', type: "string", required: true },
  { key: 'shortDescription', label: 'Short Description', type: "string", required: true },
  { key: 'description', label: 'Description', type: "string", required: true },
  { key: 'type', label: 'Type', type: "string", required: true },
  { key: 'name', label: 'Name', type: "string", required: true },
  { key: 'category', label: 'Category', type: "string", required: true },
  { key: 'timeMarker', label: 'Time Marker', type: "string", required: true },
  { key: 'pin', label: 'Pin', type: "string", required: true },
  { key: 'customerNo', label: 'Customer No', type: "string", required: true },
  { key: 'customerName', label: 'Customer Name', type: "string", required: true },
  { key: 'customerAddress', label: 'Customer Address', type: "string", required: true },
  { key: 'customerAddressGeoLong', label: 'Customer Address Geo Long', type: "string", required: true },
  { key: 'customerAddressGeoLat', label: 'Customer Address Geo Lat', type: "string", required: true },
  { key: 'customerPhone', label: 'Customer Phone', type: "string", required: true },
  { key: 'customerEmail', label: 'Customer Email', type: "string", required: true },
  { key: 'contactNo', label: 'Contact No', type: "string", required: true },
  { key: 'contactName', label: 'Contact Name', type: "string", required: true },
  { key: 'contactAddress', label: 'Contact Address', type: "string", required: true },
  { key: 'contactAddressGeoLong', label: 'Contact Address Geo Long', type: "string", required: true },
  { key: 'contactAddressGeoLat', label: 'Contact Address Geo Lat', type: "string", required: true },
  { key: 'contactPhone', label: 'Contact Phone', type: "string", required: true },
  { key: 'contactEmail', label: 'Contact Email', type: "string", required: true },
  { key: 'siteNo', label: 'Site No', type: "string", required: true },
  { key: 'siteName', label: 'Site Name', type: "string", required: true },
  { key: 'siteAddress', label: 'Site Address', type: "string", required: true },
  { key: 'siteAddressGeoLong', label: 'Site Address Geo Long', type: "string", required: true },
  { key: 'siteAddressGeoLat', label: 'Site Address Geo Lat', type: "string", required: true },
  { key: 'sitePhone', label: 'Site Phone', type: "string", required: true },
  { key: 'siteEmail', label: 'Site Email', type: "string", required: true },
  { key: 'siteRegion', label: 'Site Region', type: "string", required: true },
  { key: 'siteStreet', label: 'Site Street', type: "string", required: true },
  { key: 'siteStreetNo', label: 'Site Street No', type: "string", required: true },
  { key: 'sitePostcode', label: 'Site Postcode', type: "string", required: true },
  { key: 'siteCity', label: 'Site City', type: "string", required: true },
  { key: 'siteCounty', label: 'Site County', type: "string", required: true },
  { key: 'siteState', label: 'Site State', type: "string", required: true },
  { key: 'siteCountry', label: 'Site Country', type: "string", required: true },
  { key: 'siteFromNo', label: 'Site From No', type: "string", required: true },
  { key: 'siteFromName', label: 'Site From Name', type: "string", required: true },
  { key: 'siteFromAddress', label: 'Site From Address', type: "string", required: true },
  { key: 'siteFromAddressGeoLong', label: 'Site From Address Geo Long', type: "string", required: true },
  { key: 'siteFromAddressGeoLat', label: 'Site From Address Geo Lat', type: "string", required: true },
  { key: 'siteFromPhone', label: 'Site From Phone', type: "string", required: true },
  { key: 'siteFromEmail', label: 'Site From Email', type: "string", required: true },
  { key: 'siteFromRegion', label: 'Site From Region', type: "string", required: true },
  { key: 'siteFromStreet', label: 'Site From Street', type: "string", required: true },
  { key: 'siteFromStreetNo', label: 'Site From Street No', type: "string", required: true },
  { key: 'siteFromPostcode', label: 'Site From Postcode', type: "string", required: true },
  { key: 'siteFromCity', label: 'Site From City', type: "string", required: true },
  { key: 'siteFromCounty', label: 'Site From County', type: "string", required: true },
  { key: 'siteFromState', label: 'Site From State', type: "string", required: true },
  { key: 'siteFromCountry', label: 'Site From Country', type: "string", required: true },
  { key: 'billNo', label: 'Bill No', type: "string", required: true },
  { key: 'billName', label: 'Bill Name', type: "string", required: true },
  { key: 'billAddress', label: 'Bill Address', type: "string", required: true },
  { key: 'billAddressGeoLong', label: 'Bill Address Geo Long', type: "string", required: true },
  { key: 'billAddressGeoLat', label: 'Bill Address Geo Lat', type: "string", required: true },
  { key: 'billPhone', label: 'Bill Phone', type: "string", required: true },
  { key: 'billEmail', label: 'Bill Email', type: "string", required: true },
  { key: 'billRegion', label: 'Bill Region', type: "string", required: true },
  { key: 'importance', label: 'Importance', type: "string", required: true },
  { key: 'creationDateTime', label: 'Creation Date Time', type: "string", required: true },
  { key: 'customerReference', label: 'Customer Reference', type: "string", required: true },
  { key: 'language', label: 'Language', type: "string", required: true },
  { key: 'responsible', label: 'Responsible', type: "string", required: true },
  { key: 'creator', label: 'Creator', type: "string", required: true },
  { key: 'freeText1', label: 'Free Text1', type: "string", required: true },
  { key: 'freeText2', label: 'Free Text2', type: "string", required: true },
  { key: 'freeText3', label: 'Free Text3', type: "string", required: true },
  { key: 'freeText4', label: 'Free Text4', type: "string", required: true },
  { key: 'freeText5', label: 'Free Text5', type: "string", required: true },
  { key: 'freeText6', label: 'Free Text6', type: "string", required: true },
  { key: 'freeText7', label: 'Free Text7', type: "string", required: true },
  { key: 'freeText8', label: 'Free Text8', type: "string", required: true },
  { key: 'freeText9', label: 'Free Text9', type: "string", required: true },
  { key: 'freeText10', label: 'Free Text10', type: "string", required: true },
  { key: 'freeText11', label: 'Free Text11', type: "string", required: true },
  { key: 'freeText12', label: 'Free Text12', type: "string", required: true },
  { key: 'freeText13', label: 'Free Text13', type: "string", required: true },
  { key: 'freeText14', label: 'Free Text14', type: "string", required: true },
  { key: 'freeText15', label: 'Free Text15', type: "string", required: true },
  { key: 'freeText16', label: 'Free Text16', type: "string", required: true },
  { key: 'freeText17', label: 'Free Text17', type: "string", required: true },
  { key: 'freeText18', label: 'Free Text18', type: "string", required: true },
  { key: 'freeText19', label: 'Free Text19', type: "string", required: true },
  { key: 'freeText20', label: 'Free Text20', type: "string", required: true },
  { key: 'freeDecimal1', label: 'Free Decimal1', type: "string", required: true },
  { key: 'freeDecimal2', label: 'Free Decimal2', type: "string", required: true },
  { key: 'freeDecimal3', label: 'Free Decimal3', type: "string", required: true },
  { key: 'freeDecimal4', label: 'Free Decimal4', type: "string", required: true },
  { key: 'freeDecimal5', label: 'Free Decimal5', type: "string", required: true },
  { key: 'freeDate1', label: 'Free Date1', type: "string", required: true },
  { key: 'freeDate2', label: 'Free Date2', type: "string", required: true },
  { key: 'freeDate3', label: 'Free Date3', type: "string", required: true },
  { key: 'freeDate4', label: 'Free Date4', type: "string", required: true },
  { key: 'freeDate5', label: 'Free Date5', type: "string", required: true },
  { key: 'freeBit1', label: 'Free Bit1', type: "string", required: true },
  { key: 'freeBit2', label: 'Free Bit2', type: "string", required: true },
  { key: 'freeBit3', label: 'Free Bit3', type: "string", required: true },
  { key: 'freeBit4', label: 'Free Bit4', type: "string", required: true },
  { key: 'freeBit5', label: 'Free Bit5', type: "string", required: true },
  { key: 'enableManualSelection', label: 'Enable Manual Selection', type: "string", required: true },
  { key: 'availableInGantt', label: 'Available In Gantt', type: "string", required: true },
  { key: 'startDate', label: 'Start Date', type: "string", required: true },
  { key: 'endDate', label: 'End Date', type: "string", required: true },
  { key: 'allowDependencies', label: 'Allow Dependencies', type: "string", required: true },
  { key: 'note', label: 'Note', type: "string", required: true },
  { key: 'overRuleGanttPlanning', label: 'Over Rule Gantt Planning', type: "string", required: true },
  { key: 'readOnly', label: 'Read Only', type: "string", required: true },

];

module.exports = {
  key: 'save_job',
  noun: 'Job',
  display: {
    label: 'Set job',
    description: 'Saves the job.',
    hidden: false,
    important: true,
  },
  operation: {
    inputFields: createFields(fields),
    perform: {
      url: createUri(constants.endpoints.job),
      method: 'POST',
      headers,
      body: createBody(fields),
    },
  },
};
